### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Danghor** [csc-training/intro-to-dl#11]
The url in this line gives a 404 error. I think it would be better to explicitly link a commit where the file is present.

https://github.com/csc-training/intro-to-dl/blob/5e452784216f08dbcd5659cf687633390fd86156/day1/04-tf2-imdb-rnn.ipynb#LL9C253-L9C378

The dead link is https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/6.2-understanding-recurrent-neural-networks.ipynb

**Comment by jmakoske** [comment]
Thanks! Fixed the link.
